### PR TITLE
Clarify language around retrieval rules for non-reserved keys

### PR DESCRIPTION
**Pull request by jjhursey**

### CODE REVIEW

**Comment by jjhursey** [comment]
@dsolt This is ready to merge into your branch whenever you are ready.

**Comment by jjhursey** [comment]
@dsolt Can we merge this into your working branch?

**Comment by jjhursey** [comment]
Did this already get incorporated?

**Comment by jjhursey** [comment]
@dsolt Did this get pulled into the lastest revision? Should it be closed?

**Comment by dsolt** [comment]
cherry-picked in after rebasing

**Pull request closed without merging**
